### ISSUE TITLE
Incorrect log type classification of "ChannelAuditLog" and "FileAuditActions" in the audit log.

### ISSUE THREAD

**Issue by YoshikiEguchi** [SumoLogic/sumologic-slack#15]
Hi,
It seems that log type of  channel audit log and file audit log is  not classified correctly. Due to that, wrong log type is set so some dashboard in Sumo Web UI is not working well (I'm trying to monitor Slack Enterprise by Sumo recently so I noticed this).  

https://github.com/SumoLogic/sumologic-slack/blob/f2c87f9c3a72ed1c090c3fa10a1cf70373e19003/sumoslack/main.py#L178-L181

I think these would be opposite.
Attribute FileAuditActions should set if actionName is "file".
The correct code would be just like as:

```python
elif hasattr(self, "ChannelAuditActions") and action in self.ChannelAuditActions:
	entry["logType"] = "ChannelAuditLog"
elif hasattr(self, "FileAuditActions") and action in self.FileAuditActions:
	entry["logType"] = "FileAuditLog"
```

Thanks.

**Comment by himanshu219** [comment]
Thanks this got fixed in https://github.com/SumoLogic/sumologic-slack/pull/18
