### ISSUE TITLE
"BackfillDays" doesn't work for access_logs.

### ISSUE THREAD

**Issue by kosuke-osada** [SumoLogic/sumologic-slack#6]
In the SAM application "sumologic-slack", you can use the parameter "BackfillDays" to set how many days ago the retrieval starts from the log, but unfortunately this parameter is not working for the access log. No matter which number you set, it doesn't work.

<img width="907" alt="sam_sumo-slack_backfilldays" src="https://user-images.githubusercontent.com/49811251/85966610-42fc9200-b9fb-11ea-9095-345e89a91062.png">

As far as I can see, this applicaiton went all the way back to when we first opened the slack account.

<img width="2133" alt="sam_sumo-slack_backfilldays3" src="https://user-images.githubusercontent.com/49811251/85966967-3f1d3f80-b9fc-11ea-83df-22832cd578d1.png">
<img width="2132" alt="sam_sumo-slack_backfilldays4" src="https://user-images.githubusercontent.com/49811251/85966973-45132080-b9fc-11ea-9296-323665925ebb.png">

If this situation continues, it will take a long time to start capturing new logs, and the amount of data captured to Sumo Logic will increase rapidly due to unintended log capturing.

**Comment by kosuke-osada** [comment]
I forgot to write this, but this is what I found in version 1.0.6.

**Comment by SumoSourabh** [comment]
Thanks for the feedback. We will release the new version with support for BackFill Days in New release.

**Comment by kosuke-osada** [comment]
@SumoSourabh Thanks for the update! I am looking forward to the new release.

**Comment by SumoSourabh** [comment]
Added as part of - https://github.com/SumoLogic/sumologic-slack/pull/10
