### ISSUE TITLE
Management of versions and create release tags.

### ISSUE THREAD

**Issue by kosuke-osada** [SumoLogic/sumologic-slack#7]
Would you please manage versions of SAM applications, and create release tags in GitHub.
https://github.com/SumoLogic/sumologic-slack/releases

Sumo Logic occasionally updates the SAM application version by fixing bugs or updating code. Unfortunately, AWS SAM applications don't have the ability to notify users of an update or know what has changed.

Could you please use GitHub's Release feature to track versions and announce changes?
We need to follow important updates.

It doesn't matter what the content is, but I would be happy if there is a description of the release like the one below.
https://github.com/onelogin/wordpress-saml/releases

If I may wish, it would be helpful for many users to include the upgrade instructions in README.

**Comment by kosuke-osada** [comment]
@SumoSourabh I think you are working on correcting BACKFILLDAYS in the "audit _ changes" branch.
Thanks a lot.

Our Sumo Logic customers have a request that the Release information should be posted on GitHub as well. It would be nice if you could use the Release feature of GitHub to write the release information. 

Don't you start it from v1.0.7?

**Comment by SumoSourabh** [comment]
Release done for 1.0.7
