### ISSUE TITLE
Encryption of environment variables

### ISSUE THREAD

**Issue by kazuhito-sato** [SumoLogic/sumologic-slack#8]
The application uses "TOKEN", which are Slack credentials, but unfortunately do not support encryption.
A user with access to an AWS Lambda function could easily see the token.

<img width="1238" alt="Environment variables" src="https://user-images.githubusercontent.com/56674112/86553667-54f3ad00-bf86-11ea-88a3-aec1d0f3da21.png">

<img width="733" alt="Encryption" src="https://user-images.githubusercontent.com/56674112/86553781-a734ce00-bf86-11ea-9b39-67a12e806211.png">

It is better to encrypt TOKEN using KMS.
* Enable "Encryption in transit"
* Encrypt "TOKEN"

The following documentation may be helpful.
https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-encryption

One of the modifications to the program will be the decryption process.

**Comment by kosuke-osada** [comment]
We really need this feature.
This function is very important. It is inappropriate to store API keys in production without encryption.

**Comment by SumoSourabh** [comment]
On Hold. Will be taken up in next release.

**Comment by kosuke-osada** [comment]
@SumoSourabh Thanks for the update.
We look forward to be able to use KMS encryption soon!

**Comment by kazuhito-sato** [comment]
@SumoSourabh Has there been any progress?

**Comment by SumoSourabh** [comment]
@kazuhito-sato The idea is marked within out team backlog and will be fixed all other SAM apps (as it uses a common infrastructure). We will keep you posted on the exact delivery timeline for the solution after discussion within the team.

**Comment by kosuke-osada** [comment]
@SumoSourabh It's been about a month since the last comment, but when will the SAM app for Slack support KMS?

We use about 40 SAM apps because we need log collection settings for each Workspace. I want to update them all at once, so I'm looking forward to an early response.

Please tell me the latest situation.

**Comment by SumoSourabh** [comment]
@kosuke-osada Sorry for the delay. I spoke to my manager regarding the issue.

Can you please raise a Support ticket for the issue with the help of your customer success manager?

This will help us to prioritise the issue.

**Comment by kosuke-osada** [comment]
@SumoSourabh Thanks for the update. I issued a new support request #55246. 
I hope that the priority will be raised and you will be able to develop as soon as possible.

**Comment by SumoSourabh** [comment]
@kosuke-osada Thank you for raising the ticket.

**Comment by SumoSourabh** [comment]
@kosuke-osada We were looking into possible ways to encrypt the data for SAM app. There are two approaches, 

1.  KMS + Parameter Store
 - Parameter store does not have support for Secret string in CloudFormation template. So, manually the tokens need to be stored in the parameter store and parameter store key name need to be provided as an input.
 - Cost is **free** for using parameter store.
 - Manual operation need to be performed before installing SAM template.

2. KMS + Secrets manager
 - Secret manager has support for CloudFormation template. We can create secret using CloudFormation template.
 - Cost is **$0.40 per secret per month**.
 - No manual steps.

KMS has cost of **$1 / month / key**. 
API calls to fetch secrets cost **$0.05 per 10,000 API calls**.

Just thought of checking with you, what approach you would like to see in the SAM app?

I am having discussion within the team also.

**Comment by kosuke-osada** [comment]
@SumoSourabh I am so sorry for late reply. We suggest that it should be better to encrypt keys with pattern 2. "KMS + Secrets manager".

**Comment by SumoSourabh** [comment]
Thank you @kosuke-osada. We have the change in our roadmap now and will keep you updated on the change availability .

**Comment by SumoSourabh** [comment]
Released 1.1.0 version with the KMS + Secret Manager
