### ISSUE TITLE
Including "DBNAME" in "Application settings"

### ISSUE THREAD

**Issue by kazuhito-sato** [SumoLogic/sumologic-slack#9]
Currently, there is no "DBNAME" in the "Application settings" when deploying.
You have to add an environment variable called "DBNAME" by yourself after deploying the application.

![Application settings](https://user-images.githubusercontent.com/56674112/86692783-0e18bc80-c045-11ea-8c59-5dd7d7f5dd41.png)

When you deploy multiple applications, you need to be careful.
If you forget to add the "DBNAME", the same database, "sumoslack" by default, will be shared by multiple applications, which will cause problems.

It is better to include "DBNAME" in the "Application settings" so that you do not forget to add it.

**Comment by kosuke-osada** [comment]
That's a good idea.
My idea is that DynamoDB is used in the background, so you don't have to look at it. It is common to capture logs from multiple Workspaces, so you don't have to specify a DBNAME yourself, do you?

Can I automatically give a unique DBNAME when I deploy a Sumo Logic program?
For example, a name, date, or UUID such as "SumoLogic-Slack-20200707-02B19532-BB75-4F91-834D-172A56F40B46".

This will allow users to deploy Lambda without having to worry about DBNAME.

**Comment by SumoSourabh** [comment]
@kosuke-osada @kazuhito-sato We will look at all 4 request in version 1.0.7.

It can take up some time as I have to clean up current backlog to take the changes up.

**Comment by kazuhito-sato** [comment]
@SumoSourabh Thank you for your quick reply. I'm looking forward to the update.

It would be great if it was completed by the end of this month.

**Comment by SumoSourabh** [comment]
DBName and BackFill days changes are already incorporated and testing is also done. Minor changes.

I will look into Encryption of Token in Lambda (CF level encryption also implemented). This seems a little tricky.

If encryption is a lot of work, we will take it up in next release (1.0.8) and release 1.0.7(with DBNAME, BackFill Days and CF level Encryption) by EOW or Next week(depends on research done on Encryption)

**Comment by kosuke-osada** [comment]
@SumoSourabh I understood your schedule. We are looking forward to the new release.
Thank you for your cooperation.

**Comment by SumoSourabh** [comment]
Added as part of 1.0.7 - https://github.com/SumoLogic/sumologic-slack/pull/10
